// ============================================================
// TeraHub build script
// Generates config.js from environment variables at build time.
//
// On Netlify: set these variables in Site settings > Environment variables.
// Locally: create a .env file (see .env.example) and run: node build.js
//
// config.js is gitignored and must never be committed.
// ============================================================

const fs = require("fs");
const path = require("path");

// Minimal .env loader (no external dependency).
(function loadDotEnv() {
  const envPath = path.join(__dirname, ".env");
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, "utf8").split(/\r?\n/);
  for (const line of lines) {
    if (/^\s*#/.test(line) || !line.trim()) continue;
    const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (!m) continue;
    const key = m[1];
    let value = (m[2] || "").trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
})();

function env(name, fallback) {
  const value = process.env[name];
  if (value === undefined || value === "") {
    return fallback === undefined ? "" : fallback;
  }
  return value;
}

function bool(name, fallback) {
  const value = process.env[name];
  if (value === undefined || value === "") return fallback;
  return String(value).toLowerCase() === "true";
}

function int(name, fallback) {
  const value = parseInt(process.env[name], 10);
  return Number.isFinite(value) ? value : fallback;
}

const config = {
  firebase: {
    apiKey: env("FIREBASE_API_KEY"),
    authDomain: env("FIREBASE_AUTH_DOMAIN"),
    databaseURL: env("FIREBASE_DATABASE_URL"),
    projectId: env("FIREBASE_PROJECT_ID"),
    storageBucket: env("FIREBASE_STORAGE_BUCKET"),
    messagingSenderId: env("FIREBASE_MESSAGING_SENDER_ID"),
    appId: env("FIREBASE_APP_ID"),
    measurementId: env("FIREBASE_MEASUREMENT_ID"),
  },
  adsense: {
    publisherId: env("GOOGLE_ADSENSE_PUBLISHER_ID"),
    headerSlot: env("GOOGLE_ADSENSE_HEADER_SLOT"),
    sidebarSlot: env("GOOGLE_ADSENSE_SIDEBAR_SLOT"),
    feedSlot: env("GOOGLE_ADSENSE_FEED_SLOT"),
    headerEnabled: bool("AD_HEADER_ENABLED", true),
    sidebarEnabled: bool("AD_SIDEBAR_ENABLED", true),
    feedEnabled: bool("AD_FEED_ENABLED", false),
    feedInterval: int("AD_FEED_INTERVAL", 4),
  },
  appSettings: {
    appName: env("APP_NAME", "TeraHub"),
    environment: env("APP_ENVIRONMENT", "production"),
    debug: bool("APP_DEBUG", false),
  },
  // SHA-256 hex (64 chars) of the admin password, OR the legacy djb2 hash.
  // Generate a SHA-256 hash at: https://emn178.github.io/online-tools/sha256.html
  adminPasswordHash: env("ADMIN_PASSWORD_HASH", ""),
};

const output =
  "// AUTO-GENERATED by build.js — DO NOT EDIT OR COMMIT THIS FILE\n" +
  "// Generated: " + new Date().toISOString() + "\n" +
  "window.TERAHUB_CONFIG = " + JSON.stringify(config, null, 2) + ";\n";

fs.writeFileSync(path.join(__dirname, "config.js"), output, "utf8");
console.log("build.js: config.js generated successfully.");
