// ============================================================
// TeraHub Configuration EXAMPLE
//
// NOTE: config.js is normally AUTO-GENERATED by build.js from
// environment variables (.env locally, or Netlify env vars).
// This file documents the generated shape and can be copied to
// config.js manually if you are not using the build step.
//
// Never commit the real config.js.
// ============================================================

window.TERAHUB_CONFIG = {
  firebase: {
    apiKey: "YOUR_FIREBASE_API_KEY",
    authDomain: "your-project.firebaseapp.com",
    databaseURL: "https://your-project-default-rtdb.region.firebasedatabase.app",
    projectId: "your-project-id",
    storageBucket: "your-project.appspot.com",
    messagingSenderId: "YOUR_SENDER_ID",
    appId: "YOUR_APP_ID",
    measurementId: "YOUR_MEASUREMENT_ID"
  },
  adsense: {
    publisherId: "ca-pub-YOUR_PUBLISHER_ID",
    headerSlot: "YOUR_HEADER_SLOT_ID",
    sidebarSlot: "YOUR_SIDEBAR_SLOT_ID",
    feedSlot: "YOUR_FEED_SLOT_ID",
    headerEnabled: true,
    sidebarEnabled: true,
    feedEnabled: false,
    feedInterval: 4
  },
  appSettings: {
    appName: "TeraHub",
    environment: "production",
    debug: false
  },
  // SHA-256 hex hash (64 chars) of your admin password, or a legacy djb2 hash.
  // Never store the plaintext password here.
  adminPasswordHash: "YOUR_SHA256_PASSWORD_HASH_HERE"
};
