import nextEnv from "@next/env";

const { loadEnvConfig } = nextEnv;

loadEnvConfig(process.cwd());

const publicVariables = {
  NEXT_PUBLIC_FIREBASE_API_KEY: "FIREBASE_API_KEY",
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "FIREBASE_AUTH_DOMAIN",
  NEXT_PUBLIC_FIREBASE_DATABASE_URL: "FIREBASE_DATABASE_URL",
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "FIREBASE_PROJECT_ID",
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "FIREBASE_STORAGE_BUCKET",
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "FIREBASE_MESSAGING_SENDER_ID",
  NEXT_PUBLIC_FIREBASE_APP_ID: "FIREBASE_APP_ID",
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "FIREBASE_MEASUREMENT_ID",
  NEXT_PUBLIC_GOOGLE_ADSENSE_PUBLISHER_ID: "GOOGLE_ADSENSE_PUBLISHER_ID",
  NEXT_PUBLIC_GOOGLE_ADSENSE_HEADER_SLOT: "GOOGLE_ADSENSE_HEADER_SLOT",
  NEXT_PUBLIC_GOOGLE_ADSENSE_SIDEBAR_SLOT: "GOOGLE_ADSENSE_SIDEBAR_SLOT",
  NEXT_PUBLIC_GOOGLE_ADSENSE_FEED_SLOT: "GOOGLE_ADSENSE_FEED_SLOT",
  NEXT_PUBLIC_AD_HEADER_ENABLED: "AD_HEADER_ENABLED",
  NEXT_PUBLIC_AD_SIDEBAR_ENABLED: "AD_SIDEBAR_ENABLED",
  NEXT_PUBLIC_AD_FEED_ENABLED: "AD_FEED_ENABLED",
  NEXT_PUBLIC_AD_FEED_INTERVAL: "AD_FEED_INTERVAL",
  NEXT_PUBLIC_ADMIN_PASSWORD_HASH: "ADMIN_PASSWORD_HASH",
};

export default {
  env: Object.fromEntries(
    Object.entries(publicVariables).map(([publicName, sourceName]) => [
      publicName,
      process.env[publicName] || process.env[sourceName] || "",
    ]),
  ),
};